INSERT INTO CONTACT  VALUES ('FREELANCE', 1, 'Baraki', 'Souilah', 'Yacine', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 2, 'Baraki', 'Emmalyn', 'Delilah', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 3, 'Baraki', 'Clare', 'Idony', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 4, 'Beglium', 'Grover', 'Sydnie', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 5, 'USA', 'Missie', 'Benton', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 6, 'CANADA', 'Laurena', 'Dulcibella', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 7, 'FRANCE', 'Randell', 'Leanna', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 8, 'FRANCE', 'Michelyne', 'Elaina', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 9, 'GERMANY', 'Shirley', 'Esme', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 10, 'ICELAND', 'Brycen', 'Charlee', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 11, 'ICELAND', 'Hale', 'Luanne', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 12, 'GERMANY', 'Sam', 'Nigellus', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 13, 'TUNIS', 'Ina', 'Denzil', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 14, 'TUNIS', 'Sherman', 'Karissa', 123);
INSERT INTO CONTACT  VALUES ('FREELANCE', 15, 'INDIA', 'Audrea', 'Marissa', 123);


INSERT INTO ENTERPRISE  VALUES (1, 'Polyscripts' ,'Bruxel', 111);
INSERT INTO ENTERPRISE  VALUES (2, 'Proxify' ,'Sweden', 222);
INSERT INTO ENTERPRISE  VALUES (3, 'Google' ,'California', 333);
INSERT INTO ENTERPRISE  VALUES (4, 'Facebook' ,'California', 444);
INSERT INTO ENTERPRISE  VALUES (5, 'Yassir' ,'Algeria', 555);


--pswd test for both
INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES
(1, 'admin', '$2a$10$cet1n0fd8j6QLH21rjmJq.mGkvaQfXXh0uI4wNV2PNpeFlVsgVQGO'),
(2, 'user','$2a$10$cet1n0fd8j6QLH21rjmJq.mGkvaQfXXh0uI4wNV2PNpeFlVsgVQGO');

INSERT INTO AUTHORITY (ID, AUTHORITY) VALUES (1, 'ADMIN'), (2, 'USER');

INSERT INTO USER_AUTHORITIES (USER_ID, AUTHORITY_ID) VALUES (1, 1), (2, 2);