drop table if exists contact CASCADE;
drop table if exists enterprise CASCADE;
drop table if exists enterprise_contact CASCADE;
create table contact (
    type_contact varchar(31) not null,
    id bigint generated by default as identity,
    address varchar(255),
    lastname varchar(255),
    name varchar(255),
    tva bigint not null,
    primary key (id));

create table enterprise (
    id bigint generated by default as identity,
    address varchar(255),
    name varchar(255),
    tva bigint,
    primary key (id));

create table enterprise_contact (
    enterprise_id bigint not null,
    contact_id bigint not null);

alter table enterprise_contact
    add constraint FK3qp8jvcv6bf31p4ndk75fec5l
    foreign key (contact_id)
    references contact;

alter table enterprise_contact
    add constraint FKktvfqaxj1426fjuyw7b16fk1q
    foreign key (enterprise_id)
    references enterprise;